# Session 08

## Ordinary Least Squares Using Matrices

### An example

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
sheet_name = 'Data'
file_path = 'C:/Users/Mahdi/OneDrive/Desktop/Econometrics/Econometrics II/Econometrics_II_Session_08.xlsx'

data_hw = pd.read_excel(file_path, sheet_name)

In [13]:
data_hw

X    Y
0  10   23
1  20   41
2  32   64
3  48   90
4  60  112

In [15]:
(data_hw['X'] + data_hw['Y'])

0     33
1     61
2     96
3    138
4    172
dtype: int64

### Adding intercept

In [18]:
S = np.array([[2], [3], [4]]) #Creates a 3x1 NumPy array (three rows, one column).
S

array([[2],
       [3],
       [4]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
S.shape #row x column

(3, 1)

In [24]:
S.shape[0] #row

3

In [26]:
np.ones(S.shape[0]) #row

array([1., 1., 1.])

### np.column_stack()

In [29]:
np.column_stack((S, S))

array([[2, 2],
       [3, 3],
       [4, 4]])

In [31]:
np.column_stack((S, S, S))

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [33]:
S_with_ones = np.column_stack((np.ones(S.shape[0]), S))
S_with_ones

array([[1., 2.],
       [1., 3.],
       [1., 4.]])

### Running the OLS
$$
\beta = (X^{'} X)^{-1} X^{'} Y
$$

In [36]:
X = data_hw['X']
X.head() #Shows the first 5 rows of X

0    10
1    20
2    32
3    48
4    60
Name: X, dtype: int64

In [38]:
X.shape #row

(5,)

In [40]:
type(X)

pandas.core.series.Series

In [42]:
X_with_intercept = np.column_stack((np.ones(X.shape[0]), X))
X_with_intercept[0:5]

array([[ 1., 10.],
       [ 1., 20.],
       [ 1., 32.],
       [ 1., 48.],
       [ 1., 60.]])

In [44]:
type(X_with_intercept)

numpy.ndarray

In [46]:
X_prime = X_with_intercept.T
X_prime

array([[ 1.,  1.,  1.,  1.,  1.],
       [10., 20., 32., 48., 60.]])

In [48]:
X_prime[1][1:5] #column

array([20., 32., 48., 60.])

In [50]:
X_prime_X = X_prime @ X_with_intercept
X_prime_X

array([[5.000e+00, 1.700e+02],
       [1.700e+02, 7.428e+03]])

In [52]:
inverse_of_X_prime_X = np.linalg.inv(X_prime_X)
inverse_of_X_prime_X

array([[ 9.01456311e-01, -2.06310680e-02],
       [-2.06310680e-02,  6.06796117e-04]])

In [54]:
Y = data_hw['Y']
estimators = inverse_of_X_prime_X @ X_prime @ Y
estimators

array([5.79854369, 1.77063107])

### Introduction to f-string

In [57]:
print("intercept: ", estimators[0])
print("slope: ", estimators[1])

intercept:  5.7985436893203435
slope:  1.7706310679611657


In [59]:
print(f"Intercept: {estimators[0]}")
print(f"Slope: {estimators[1]}")

Intercept: 5.7985436893203435
Slope: 1.7706310679611657


### Tranforming the data to numpy array right from the beginning

In [62]:
sheet_name = 'Data'
file_path = 'C:/Users/Mahdi/OneDrive/Desktop/Econometrics/Econometrics II/Econometrics_II_Session_08.xlsx'

data_hw = pd.read_excel(file_path, sheet_name)

In [64]:
data_hw

X    Y
0  10   23
1  20   41
2  32   64
3  48   90
4  60  112

In [66]:
data_hw['X'] #Pandas

0    10
1    20
2    32
3    48
4    60
Name: X, dtype: int64

In [68]:
data_hw['X'].values #NumPy array

array([10, 20, 32, 48, 60], dtype=int64)

In [70]:
data_hw['X'].values.shape

(5,)

In [72]:
data_hw['X'].values.reshape(-1, 1)[1:5]
#Reshape X into a column vector (auto-detect rows with -1), 1 column.
#Convert X to a 2D column vector and take rows 1 to 4.

array([[20],
       [32],
       [48],
       [60]], dtype=int64)

In [74]:
X = data_hw['X'].values.reshape(-1, 1)
X.shape #2D

(5, 1)

In [76]:
X.shape[0] #1D

5

In [78]:
Y = data_hw['Y'].values.reshape(-1, 1)
Y.shape

(5, 1)

In [80]:
type(X)

numpy.ndarray

In [82]:
X = np.column_stack((np.ones(X.shape[0]), X))
X[0:3]

array([[ 1., 10.],
       [ 1., 20.],
       [ 1., 32.]])

In [84]:
X_transpose = X.transpose()

In [86]:
inverse_X_transpose_X = np.linalg.inv(X_transpose @ X)
inverse_X_transpose_X

array([[ 9.01456311e-01, -2.06310680e-02],
       [-2.06310680e-02,  6.06796117e-04]])

In [88]:
estim = inverse_X_transpose_X @ X_transpose @ Y
print(f"Intercept: {estim[0]}")
print(f"Slope: {estim[1]}")

Intercept: [5.79854369]
Slope: [1.77063107]


In [90]:
if estim[0] == estimators[0]:
    print("Both methods calculated the same value for intercept! Well Done! :) ")
else:
    print("Each method calculated a diffrent value for intercept!")

Both methods calculated the same value for intercept! Well Done! :) 


In [92]:
if estim[1] == estimators[1]:
    print("Both methods calculated the same value for slope! Well Done! :) ")
else:
    print("Each method calculated a diffrent value for slope!")

Both methods calculated the same value for slope! Well Done! :) 


### Calculating the Sum of Squared Residuals (1st Method)

In [95]:
X

array([[ 1., 10.],
       [ 1., 20.],
       [ 1., 32.],
       [ 1., 48.],
       [ 1., 60.]])

In [97]:
estim

array([[5.79854369],
       [1.77063107]])

In [99]:
Y_hat = X @ estim
Y_hat[1:5]

array([[ 41.21116505],
       [ 62.45873786],
       [ 90.78883495],
       [112.03640777]])

In [101]:
Y

array([[ 23],
       [ 41],
       [ 64],
       [ 90],
       [112]], dtype=int64)

In [103]:
residuals = Y - Y_hat
residuals[1:5]

array([[-0.21116505],
       [ 1.54126214],
       [-0.78883495],
       [-0.03640777]])

In [105]:
SSR = residuals.T @ residuals
print(SSR)
print(f"e'e or sum squared residulas is equal to {SSR}")

[[3.29854369]]
e'e or sum squared residulas is equal to [[3.29854369]]


### M Matrix that is idempotent and symmetric
$$
e = Y - \hat{Y} 
= Y - X (X^{'} X)^{-1} X^{'} Y 
= [I - X (X^{'} X)^{-1} X^{'}] Y 
= MY
$$
$$
A @ A = A : Idempotent
$$
$$
A = A^{-1} : Symmetric
$$

In [108]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [110]:
X

array([[ 1., 10.],
       [ 1., 20.],
       [ 1., 32.],
       [ 1., 48.],
       [ 1., 60.]])

In [112]:
X.shape

(5, 2)

In [114]:
X.shape[0]

5

In [116]:
I = (np.eye(X.shape[0]))
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [118]:
M = I - X @ inverse_X_transpose_X @ X_transpose
M

array([[ 0.45048544, -0.4038835 , -0.22912621,  0.0038835 ,  0.17864078],
       [-0.4038835 ,  0.68106796, -0.21699029, -0.08106796,  0.02087379],
       [-0.22912621, -0.21699029,  0.79757282, -0.18300971, -0.1684466 ],
       [ 0.0038835 , -0.08106796, -0.18300971,  0.68106796, -0.42087379],
       [ 0.17864078,  0.02087379, -0.1684466 , -0.42087379,  0.38980583]])

In [120]:
M[0:5, 4: 5]

array([[ 0.17864078],
       [ 0.02087379],
       [-0.1684466 ],
       [-0.42087379],
       [ 0.38980583]])

In [122]:
squared_M = M @ M
squared_M[0:5, 0:5]

array([[ 0.45048544, -0.4038835 , -0.22912621,  0.0038835 ,  0.17864078],
       [-0.4038835 ,  0.68106796, -0.21699029, -0.08106796,  0.02087379],
       [-0.22912621, -0.21699029,  0.79757282, -0.18300971, -0.1684466 ],
       [ 0.0038835 , -0.08106796, -0.18300971,  0.68106796, -0.42087379],
       [ 0.17864078,  0.02087379, -0.1684466 , -0.42087379,  0.38980583]])

In [124]:
(squared_M @ M @ M)[0:5, 0:5]

array([[ 0.45048544, -0.4038835 , -0.22912621,  0.0038835 ,  0.17864078],
       [-0.4038835 ,  0.68106796, -0.21699029, -0.08106796,  0.02087379],
       [-0.22912621, -0.21699029,  0.79757282, -0.18300971, -0.1684466 ],
       [ 0.0038835 , -0.08106796, -0.18300971,  0.68106796, -0.42087379],
       [ 0.17864078,  0.02087379, -0.1684466 , -0.42087379,  0.38980583]])

### Calculating the Sum of Squared Residuals (2nd Method)
$$
e'e = Y'MY
$$

In [127]:
(M @ Y)[:5,]

array([[-0.50485437],
       [-0.21116505],
       [ 1.54126214],
       [-0.78883495],
       [-0.03640777]])

In [129]:
e_prime_e = Y.T @ M @ Y
e_prime_e

array([[3.29854369]])

In [131]:
if e_prime_e == SSR: #NumPy array
    print("Both methods calculated the same value!")
else:
    print("Each method calculated a different value!!!")

Each method calculated a different value!!!


### Estimating the intercept and coefficient(slope) for a population
First we Create two populations for independent variables

In [188]:
np.random.seed(54)
n = 10000
X1 = np.random.laplace(0, 14, n)
#Generate 10,000 samples from a Laplace distribution (mean=0, scale=14).
X1

array([ -2.43484984,  -4.47363995, -13.92886668, ...,   5.55465129,
        14.93664089,  -4.75034346])

In [136]:
X2 = np.random.rand(n, 1)
#Generate 10,000 random numbers uniformly between 0 and 1 as a column vector.
print(X2.shape)
X2

(10000, 1)


array([[0.65295177],
       [0.14433767],
       [0.72235766],
       ...,
       [0.17561502],
       [0.31561183],
       [0.42667603]])

### Setting the population parameters

In [139]:
alpha = 0.7
beta1 = 1.2
beta2 = 1.7

Y_1 = alpha + beta1 * X1 + beta2 * X2
Y_1

array([[ -1.11180181,  -3.55834993, -14.904622  , ...,   8.47559955,
         19.73398707,  -3.89039414],
       [ -1.97644578,  -4.4229939 , -15.76926597, ...,   7.61095558,
         18.8693431 ,  -4.75503811],
       [ -0.99381178,  -3.44035991, -14.78663198, ...,   8.59358957,
         19.85197709,  -3.77240412],
       ...,
       [ -1.92327428,  -4.3698224 , -15.71609447, ...,   7.66412708,
         18.9225146 ,  -4.70186661],
       [ -1.68527971,  -4.13182783, -15.4780999 , ...,   7.90212165,
         19.16050917,  -4.46387204],
       [ -1.49647056,  -3.94301868, -15.28929076, ...,   8.0909308 ,
         19.34931832,  -4.27506289]])

In [143]:
print(Y_1.shape)

(10000, 10000)


In [194]:
X1.shape

(10000,)

In [192]:
X2.shape

(10000, 1)

In [214]:
X1.flatten().shape
#Convert X1 into a 1D array for regression compatibility.

(10000,)

In [198]:
X2.flatten().shape

(10000,)

### We assume that the population is deterministic rather than stochastic, meaning that Y_1 is fully explained by X1 and X2.

In [200]:
Y_1_pop = alpha + beta1 * X1.flatten() + beta2 * X2.flatten() #deterministic
Y_1_pop

array([ -1.11180181,  -4.4229939 , -14.78663198, ...,   7.66412708,
        19.16050917,  -4.27506289])

### Another assumption is that, when modeling Y_1 based on explanatory variables, we do not have access to X2 and can only model Y_1 using X1. Therefore, we must account for a stochastic term when modeling Y_1 based on X1—this term, epsilon, follows a stochastic process.
در دنیای واقعی ما به همه‌ی متغیرها دسترسی نداریم

In [154]:
epsilon = np.random.normal(0, 1, n)
#Generate random Gaussian noise (ε) to model unobserved shocks.
#Draw n error terms from N(0,1): zero-mean, unit-variance noise.
Y_1_observed = alpha + beta1 * X1.flatten() + epsilon

### We sample X1 and Y_1_observed to simulate real-world limitations where data access is restricted. Indices are randomly chosen without replacement to form subsets for analysis. Since X2 is unavailable, we introduce a stochastic term to adjust for missing explanatory power. In reality, access to X1 and Y may also be limited, requiring such sampling approaches

In [218]:
sample_size = 100
indices = np.random.choice(100, sample_size, replace=False)
#Draw a small random subsample from the full dataset.

X1_sample = X1[indices]
#Select a subsample of X1 (incomplete data).
Y_1_sample = Y_observed[indices]
#Select the corresponding Y values for the subsample.

In [159]:
Y_1_sample.shape

(100,)

In [161]:
X1_sample.shape

(100,)

In [163]:
X1_sample_reshaped = X1_sample.reshape(100, 1)
#Reshape X into a column vector (design matrix requirement).
X1_sample_reshaped.shape

(100, 1)

In [167]:
Y_1_sample_reshaped = Y_1_sample.reshape(100, 1)
Y_1_sample_reshaped.shape

(100, 1)

### Adding intercept

In [224]:
X1_sample_reshaped.shape

(100, 1)

In [226]:
X1_sample_reshaped.shape[0]

100

In [228]:
X1_sample_reshaped_with_intercept = np.column_stack((np.ones(X1_sample_reshaped.shape[0]), X1_sample_reshaped))
#Add an intercept term to the regression matrix.
X1_sample_reshaped_with_intercept.shape

(100, 2)

$$
\beta = (X^{'} X)^{-1} X^{'} Y
$$

In [173]:
XTX_inv = np.linalg.inv(X1_sample_reshaped_with_intercept.T @ X1_sample_reshaped_with_intercept)

In [179]:
XTY = X1_sample_reshaped_with_intercept.T @ Y_1_sample_reshaped

In [181]:
intercept_and_slope = XTX_inv @ XTY

In [183]:
intercept_and_slope

array([[0.68923452],
       [1.19886161]])

In [185]:
print(f"Intercept: {intercept_and_slope[0]}")
print(f"slope: {intercept_and_slope[1]}")

Intercept: [0.68923452]
slope: [1.19886161]


## Exercise

### 1. Use the second sheet (Exercise) of the Excel file and complete the following steps:

- Calculate the intercept and coefficient using matrix operations.
- Compute the Sum of Squared Residuals (SSR) using two methods discussed in this session.

### 2. Use the second sheet (Exercise) of the Excel file and complete the following steps:
Using the data in the second sheet (Exercise) of the Excel file, complete the following steps:

- Compute the hat matrix:
$$
H = X (X'X)^{-1} X'
$$

- Compute the fitted values:
$$
\hat{Y} = H Y
$$


- Total Sum of Squares (TSS):
$$
TSS = (Y - \bar{Y})'(Y - \bar{Y})
$$
- Explained Sum of Squares (ESS):
$$
ESS = (\hat{Y} - \bar{Y})'(\hat{Y} - \bar{Y})
 $$

- R-squared:
$$
R^2 = \frac{ESS}{TSS}
$$